[tool.poetry]
name = "webserver"
version = "0.1.0"
description = ""
authors = ["ming luo <itestmycode@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
torch = "2.2.0"
colbert-ai = "0.2.19"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
